version: '3.0'
services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: intergration-test-user
      POSTGRES_DB: catalog
    ports:
      - '5432:5432'
    networks:
      - catalog-gql-net
  gateway:
    image: registry.heroku.com/marketplace-gateway/web:latest
    environment:
      - LOCAL_GQL=catalog-gql
      - LOCAL_GQL_URL=catalog-gql:5000
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - '5000:5000'
    depends_on:
      - 'catalog-gql'
    links:
      - 'catalog-gql'
    networks:
      - catalog-gql-net
  catalog-gql:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - NPM_TOKEN=$NPM_TOKEN
    image: 'catalog-gql:dev'
    ports:
      - '5001:5000'
    depends_on:
      - 'postgres'
    environment:
      - POSTGRES_DATABASE_URL=postgres://intergration-test-user:passw0rd@postgres:5432/catalog
    networks:
      - catalog-gql-net
networks:
  catalog-gql-net:
    driver: bridge
